### ISSUE TITLE
Replace Travis with pre-commit

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#429]
> you may look into [pre-commit](https://pre-commit.com/) to automatically run type checking, linting, formatting, etc. on commit

Very interesting suggestion! We currently have a similar mechanism in place on _Travis CI_, see [this dotfile](https://github.com/Wikidata/soweego/blob/9ed8b4e28fd2ea4150b37cbb49b44ce8bfb2c381/.travis.yml).
However, it's a bit hacky and doesn't run _mypy_ type hints check.
From a first glimpse, it looks like  _pre-commit_ is a much better solution:
- it can cater for CI , see https://pre-commit.com/#usage-in-continuous-integration;
- no hack seems required to autofix PRs, see https://pre-commit.com/#pre-commitci-example;
- it's claimed to be faster than Travis, see https://pre-commit.com/#pre-commitci-example.

_Originally posted by @marfox in https://github.com/Wikidata/soweego/issues/428#issuecomment-911864333_

**Comment by marfox** [comment]
I tried to reproduce the same invocation of **isort, autoflake, black** as in `.travis.yml` in the terminal, but the output is different.
```
/app/soweego# pre-commit run -a
```
Here's the `.pre-commit-config.yaml` I used:
```yaml
repos:
    - repo: https://github.com/pycqa/isort
      rev: 4.3.21
      hooks:
          - id: isort
            args: [-y, -rc, -s soweego/cli.py]
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args: [-i, -r, --remove-all-unused-imports, --remove-unused-variables]
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            args: [-S, -l 80]
```
Let'see what happens with the CI service
